apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-spring-cloud-gateway-binding
subjects:
  - kind: ServiceAccount
    name: test-spring-cloud-gateway
    namespace: microservice-gateway
roleRef:
  kind: ClusterRole
  name: test-spring-cloud-gateway
  apiGroup: rbac.authorization.k8s.io
