apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: microservice-gateway-binding
subjects:
  - kind: ServiceAccount
    name: microservice-gateway
    namespace: microservice-gateway
roleRef:
  kind: ClusterRole
  name: microservice-gateway
  apiGroup: rbac.authorization.k8s.io
