apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-spring-cloud-gateway
  namespace: microservice-gateway
  labels:
    app: test-spring-cloud-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-spring-cloud-gateway
  template:
    metadata:
      name: test-spring-cloud-gateway
      labels:
        app: test-spring-cloud-gateway
    spec:
      serviceAccountName: test-spring-cloud-gateway
      restartPolicy: Always
      containers:
        - name: test-spring-cloud-gateway
          image: test-spring-cloud-gateway:1.0.0-1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: gateway-port
              protocol: TCP
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 256Mi
